// <auto-generated />
namespace SCRIPTERS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:SCRIPTERS/Migrations/201910061657103_Initial-Migration.Designer.cs
    public sealed partial class InitialMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201910061657103_Initial-Migration"; }
=======
    public sealed partial class Imageupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Imageupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201910062127442_Imageupdate"; }
>>>>>>> 32849c0143eafecbe19775cb9f4bc79cf1a6f0e3:SCRIPTERS/Migrations/201910062127442_Imageupdate.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
